module Thralldom {
    export class ContentLibrary {
        //@StartContent
		public static Fonts = { HelvetikerJS: "Content/Fonts/Helvetiker.js",  };
		public static Models = { bore: { barrelsUVJPG: "Content/Models/bore/barrelsUV.jpg", barrelsoneJS: "Content/Models/bore/barrels_one.js", barrelstwoJS: "Content/Models/bore/barrels_two.js", fourJPG: "Content/Models/bore/four.jpg", housetwoJS: "Content/Models/bore/house_two.js", LightmapPNG: "Content/Models/bore/Lightmap.png", monasteryobjectJS: "Content/Models/bore/monastery_object.js", monasterytextureJPG: "Content/Models/bore/monastery_texture.jpg", objectHouse1JS: "Content/Models/bore/objectHouse1.js", objectMarketJS: "Content/Models/bore/objectMarket.js", objectTerrainJS: "Content/Models/bore/objectTerrain.js", oneJPG: "Content/Models/bore/one.jpg", rooftxtJPG: "Content/Models/bore/rooftxt.jpg", terraintextrJPG: "Content/Models/bore/terraintextr.jpg", threeJPG: "Content/Models/bore/three.jpg", twoJPG: "Content/Models/bore/two.jpg", wallsJPG: "Content/Models/bore/walls.jpg", },Buildings: { Barrels: { },House_01: { },House_02: { },Monastery: { },},Heroes: { Boycho: { BoychoAnimationANIM: "Content/Models/Heroes/Boycho/BoychoAnimation.anim", BoychoAnimationJS: "Content/Models/Heroes/Boycho/BoychoAnimation.js", BoychoClothJPG: "Content/Models/Heroes/Boycho/Boycho_Cloth.jpg", BoychoHeadJPG: "Content/Models/Heroes/Boycho/Boycho_Head.jpg", BoychoLeftEyeJPG: "Content/Models/Heroes/Boycho/Boycho_Left_Eye.jpg", BoychoLeftHandJPG: "Content/Models/Heroes/Boycho/Boycho_Left_Hand.jpg", BoychoPantsJPG: "Content/Models/Heroes/Boycho/Boycho_Pants.jpg", BoychoRightEyeJPG: "Content/Models/Heroes/Boycho/Boycho_Right_Eye.jpg", BoychoRightHandJPG: "Content/Models/Heroes/Boycho/Boycho_Right_Hand.jpg", BoychoTieJPG: "Content/Models/Heroes/Boycho/Boycho_Tie.jpg", PistolJPG: "Content/Models/Heroes/Boycho/Pistol.jpg", PistolAnimationJS: "Content/Models/Heroes/Boycho/PistolAnimation.js", },},Test: { BoychoAnimJS: "Content/Models/Test/BoychoAnim.js", diff201JPG: "Content/Models/Test/diff2_01.jpg", diff202JPG: "Content/Models/Test/diff2_02.jpg", diff203JPG: "Content/Models/Test/diff2_03.jpg", diff302JPG: "Content/Models/Test/diff3_02.jpg", diff303JPG: "Content/Models/Test/diff3_03.jpg", diff01JPG: "Content/Models/Test/diff_01.jpg", diff02JPG: "Content/Models/Test/diff_02.jpg", diff03JPG: "Content/Models/Test/diff_03.jpg", PistolJPG: "Content/Models/Test/Pistol.jpg", PistolAnimJS: "Content/Models/Test/PistolAnim.js", }, };
		public static Quests = { defaultJS: "Content/Quests/default.js",  };
		public static Scenes = { defaultJS: "Content/Scenes/default.js",  };
		public static Scripts = { RandomStuffSCRIPT: "Content/Scripts/RandomStuff.script",  };
		public static Textures = { Skybox: { negXPNG: "Content/Textures/Skybox/negX.png", negYPNG: "Content/Textures/Skybox/negY.png", negZPNG: "Content/Textures/Skybox/negZ.png", posXPNG: "Content/Textures/Skybox/posX.png", posYPNG: "Content/Textures/Skybox/posY.png", posZPNG: "Content/Textures/Skybox/posZ.png", },BlackWhiteCheckerJPG: "Content/Textures/BlackWhiteChecker.jpg", BlueGreenCheckerPNG: "Content/Textures/BlueGreenChecker.png", CrosshairPNG: "Content/Textures/Crosshair.png", DirtTextureJPG: "Content/Textures/DirtTexture.jpg", GrassJPG: "Content/Textures/Grass.jpg", RedCheckerPNG: "Content/Textures/RedChecker.png",  };

		//@EndContent

    }
} 