module Thralldom {
    export class ContentLibrary {
        //@StartContent
		public static Fonts = { HelvetikerJS: "Content/Fonts/Helvetiker.js",  };
		public static Models = { bore: { barrelsUVJPG: "Content/Models/bore/barrelsUV.jpg", barrelsoneJS: "Content/Models/bore/barrels_one.js", barrelstwoJS: "Content/Models/bore/barrels_two.js", fourJPG: "Content/Models/bore/four.jpg", housetwoJS: "Content/Models/bore/house_two.js", LightmapPNG: "Content/Models/bore/Lightmap.png", monasteryobjectJS: "Content/Models/bore/monastery_object.js", monasterytextureJPG: "Content/Models/bore/monastery_texture.jpg", objectHouse1JS: "Content/Models/bore/objectHouse1.js", objectMarketJS: "Content/Models/bore/objectMarket.js", objectTerrainJS: "Content/Models/bore/objectTerrain.js", oneJPG: "Content/Models/bore/one.jpg", rooftxtJPG: "Content/Models/bore/rooftxt.jpg", terraintextrJPG: "Content/Models/bore/terraintextr.jpg", threeJPG: "Content/Models/bore/three.jpg", ThumbsDB: "Content/Models/bore/Thumbs.db", twoJPG: "Content/Models/bore/two.jpg", wallsJPG: "Content/Models/bore/walls.jpg", },Engineer: { engineerJS: "Content/Models/Engineer/engineer.js", engineerheadJPG: "Content/Models/Engineer/engineer_head.jpg", engineerredJPG: "Content/Models/Engineer/engineer_red.jpg", ThumbsDB: "Content/Models/Engineer/Thumbs.db", },Spartan: { CclothPNG: "Content/Models/Spartan/Ccloth.png", CgoldPNG: "Content/Models/Spartan/Cgold.png", CnormalPNG: "Content/Models/Spartan/Cnormal.png", CskinPNG: "Content/Models/Spartan/Cskin.png", CswordPNG: "Content/Models/Spartan/Csword.png", spartanJS: "Content/Models/Spartan/spartan.js", ThumbsDB: "Content/Models/Spartan/Thumbs.db", },Test: { diff201JPG: "Content/Models/Test/diff2_01.jpg", diff202JPG: "Content/Models/Test/diff2_02.jpg", diff203JPG: "Content/Models/Test/diff2_03.jpg", diff302JPG: "Content/Models/Test/diff3_02.jpg", diff303JPG: "Content/Models/Test/diff3_03.jpg", diff01JPG: "Content/Models/Test/diff_01.jpg", diff02JPG: "Content/Models/Test/diff_02.jpg", diff03JPG: "Content/Models/Test/diff_03.jpg", PistolJPG: "Content/Models/Test/Pistol.jpg", TestEightJS: "Content/Models/Test/TestEight.js", ThumbsDB: "Content/Models/Test/Thumbs.db", }, };
		public static Quests = { defaultJS: "Content/Quests/default.js",  };
		public static Scenes = { defaultJS: "Content/Scenes/default.js",  };
		public static Textures = { Skybox: { negXPNG: "Content/Textures/Skybox/negX.png", negYPNG: "Content/Textures/Skybox/negY.png", negZPNG: "Content/Textures/Skybox/negZ.png", posXPNG: "Content/Textures/Skybox/posX.png", posYPNG: "Content/Textures/Skybox/posY.png", posZPNG: "Content/Textures/Skybox/posZ.png", ThumbsDB: "Content/Textures/Skybox/Thumbs.db", },BlackWhiteCheckerJPG: "Content/Textures/BlackWhiteChecker.jpg", BlueGreenCheckerPNG: "Content/Textures/BlueGreenChecker.png", CrosshairPNG: "Content/Textures/Crosshair.png", DirtTextureJPG: "Content/Textures/DirtTexture.jpg", GrassJPG: "Content/Textures/Grass.jpg", RedCheckerPNG: "Content/Textures/RedChecker.png", ThumbsDB: "Content/Textures/Thumbs.db",  };

		//@EndContent

    }
} 